### ISSUE TITLE
breaks on any value other than a string

### ISSUE THREAD

**Issue by radiovisual** [ryanflorence/actually-this-is-a-number#1]
The following statement should return a number:

``` js
actuallyThisIsANumber(10000);
```

(because, actually, `10000` **_IS_** a number) :smile: 

but instead returns: 

`TypeError: undefined is not a function`

The error is happening because you [are attempting to run the `replace()` method on a number](https://github.com/ryanflorence/actually-this-is-a-number/blob/master/index.js#L2), but the `replace()` method is only available to string objects.

Along these same lines, you get the same error if you attempt to pass anything other than a string:

``` js
actuallyThisIsANumber({});
//=> TypeError: undefined is not a function
```

So a simple check/throw could be nice, because if it's going throw an error anyway, it might as well throw something useful to developers:

```
TypeError: actually-this-is-a-number expects a string
```

**Comment by radiovisual** [comment]
btw: I am happy to submit a pull request (if applicable).

**Comment by radiovisual** [comment]
no love here?

**Comment by radiovisual** [comment]
I am going to assume that this module is unmaintained/abandoned, since I opened this issue 2 months ago and haven't heard anything at all, so I wrote [just-numbers](https://github.com/radiovisual/just-numbers) to fill the void in my heart. :broken_heart:

**Comment by ryanflorence** [comment]
Ha, this was a joke...
